<?php 

// Done at: 2026-05-27

// 389. Find the Difference

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.


class Solution {

    /**
     * @param String $s
     * @param String $t
     * @return String
     */
    function findTheDifference_v1($s, $t) {
        $a1=[];
        $a2=[];

        for($i=0;$i<strlen($s);$i++){
            if(!isset($a1[$s[$i]])){
                $a1[$s[$i]] = 1;
            }else{
                $a1[$s[$i]] += 1;
            }
        }
        for($i=0;$i<strlen($t);$i++){
            if(!isset($a2[$t[$i]])){
                $a2[$t[$i]] = 1;
            }else{
                $a2[$t[$i]] += 1;
            }
        }

        foreach($a2 as $letter => $qtd){
            if(!isset($a1[$letter]) || ($a1[$letter] != $qtd))
                return $letter;
        }
    }

    function findTheDifference($s, $t) {
        $countS = [];
        $countT = [];

        foreach (str_split($s) as $char) {
            $countS[$char] = ($countS[$char] ?? 0) + 1;
        }

        foreach (str_split($t) as $char) {
            $countT[$char] = ($countT[$char] ?? 0) + 1;
        }

        foreach ($countT as $char => $count) {

            if (
                !isset($countS[$char]) ||
                $countS[$char] !== $count
            ) {
                return $char;
            }
        }
    }
}

$s = "abcd"; $t = "abcde"; //e
$s = ""; $t = "y"; //y

$solution = new Solution();
$result = $solution->findTheDifference($s,$t);

var_dump($result);