version: "3.3"

services:
  nginx:
    build: 
        dockerfile: ./nginx.dockerfile
        context: .
    image: ngnix
    container_name: nginx-score
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./default-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks: 
      app-network:
        ipv4_address: 11.1.0.101
    depends_on: 
      - "app"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app
    container_name: app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html/public
    command: php-fpm
    ports:
      - "9000"
    networks: 
      app-network:
        ipv4_address: 11.1.0.102 
    depends_on: 
      - "mysql"

  mysql:
    image: mysql:5.7.22
    command: --max_allowed_packet=32505856
    container_name: mysql
    hostname: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
    volumes:
      - ../Projects/app/mysql/data/db/:/var/lib/mysql/
      - ../Projects/app/mysql/dump/:/docker-entrypoint-initdb.d/ 
    restart: always
    networks:
      app-network:
        ipv4_address: 11.1.0.103
    
networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.1.0.0/24
