version: "3.3"

services:
  nginx:
    build: 
        dockerfile: ./environment/nginx/Dockerfile
        context: .
    image: ngnix
    container_name: nginx
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./environment/nginx/default-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./environment/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks: 
      app-network:
        ipv4_address: 21.1.0.101
    depends_on: 
      - "app"

  app:
    build:
      context: .
      dockerfile: ./environment/app/Dockerfile
    image: app
    container_name: app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: php-fpm
    ports:
      - "9000"
    networks: 
      app-network:
        ipv4_address: 21.1.0.102 
    depends_on: 
      - "mysql"

  mysql:
    image: mysql:5.7.22
    command: --max_allowed_packet=32505856
    container_name: mysql
    hostname: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
    volumes:
      - ~/volumes/app/mysql/data/db/:/var/lib/mysql/
      - ~/volumes/app/mysql/dump/:/docker-entrypoint-initdb.d/ 
    # restart: always
    networks:
      app-network:
        ipv4_address: 21.1.0.103
    
  supervisor: 
    image: app
    container_name: supervisor
    environment:
      CONTAINER_ROLE: default-queue  
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html  
    networks: 
      app-network:
        ipv4_address: 21.1.0.104
    depends_on: 
      - "app" 

  scheduler: 
    image: app
    container_name: scheduler
    environment:
      CONTAINER_ROLE: scheduler  
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html  
    networks: 
      app-network:
        ipv4_address: 21.1.0.105
    depends_on: 
      - "app"

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 21.1.0.0/24
