version: "3.3"

services:
  nginx:
    build: 
        context: .
        dockerfile: ./environment/nginx/Dockerfile
    image: ngnix
    container_name: nginx
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./environment/nginx/default-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./environment/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks: 
      application-network:
        ipv4_address: 17.1.0.101
    depends_on: 
      - "application"

  application:
    build:
      context: .
      dockerfile: ./environment/application/Dockerfile
    image: application
    container_name: application
    volumes:
      - ./:/var/www/html
      - ./environment/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/html
    command: php-fpm
    ports:
      - "9000"
    networks: 
      application-network:
        ipv4_address: 17.1.0.102 
    depends_on: 
      - "sqlserver"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    hostname: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - ~/volumes/application/sqlserver/data/:/var/opt/mssql 
    networks:
      application-network:
        ipv4_address: 17.1.0.103 

networks:
  application-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 17.1.0.0/24