apiVersion: apps/v1
kind: Deployment
metadata: 
  name: laravel
  labels:
    tier: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: laravel
      tier: backend
  template:
    metadata:
      labels:
        app: laravel
        tier: backend
    spec:
      containers:
        - name: laravel
          image: lucasfer/laravel_app:latest
          envFrom:
            - configMapRef:
                name: laravel-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: laravel
  labels:
    app: laravel 
    tier: backend
spec: 
  selector:
    app: laravel 
    tier: backend
  ports:
    - protocol: TCP
      port: 9000
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-configmap
data:
  APP_DEBUG: "false"
  APP_ENV: "local"
  APP_KEY: "base64:nQKCOivp3DJkaRqGmYfEBPu++2gCy3wUrADJn8crvfI="
  APP_NAME: "My App"
  APP_URL: "http://192.168.59.100:80/api"
  DB_CONNECTION: "mysql"
  DB_DATABASE: "laravel"
  DB_HOST: "mysql"
  DB_PASSWORD: "123456"
  DB_PORT: "3306"
  DB_USERNAME: "root"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "database"