apiVersion: v1
kind: Pod
metadata: 
  name: laravel
  labels:
    app: laravel
spec:
  containers:
    - name: laravel
      image: lucasfer/laravel_app:latest
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: laravel-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: laravel
  labels:
    app: laravel
    tier: web
spec:
  type: NodePort
  selector:
    app: laravel
    tier: web
  ports:
    - port: 80
      nodePort: 30000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-configmap
data:
  APP_DEBUG: "false"
  APP_ENV: "local"
  APP_KEY: "base64:nQKCOivp3DJkaRqGmYfEBPu++2gCy3wUrADJn8crvfI="
  APP_NAME: "My App"
  APP_URL: "http://192.168.59.100:30000"
  DB_CONNECTION: "mysql"
  DB_DATABASE: "laravel"
  DB_HOST: "mysql"
  DB_PASSWORD: "123456"
  DB_PORT: "3306"
  DB_USERNAME: "root"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "database"