apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: laravel
spec:
  selector:
    app: nginx 
  ports:
  - protocol: TCP
    port: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  labels:
    app: laravel
data:
  config : |
    server {
      listen 80;
      index index.php index.html;

      location /api {
          try_files $uri $uri/ /index.php?$query_string;
      }

      location ~ \.php$ {
          include fastcgi_params;
          fastcgi_connect_timeout 40s;
          fastcgi_read_timeout 10s;
          fastcgi_buffers 256 4k;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass laravel:9000;
        }
    }