apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-configmap
data:
  APP_DEBUG: "true"
  APP_ENV: "local"
  APP_KEY: "base64:nQKCOivp3DJkaRqGmYfEBPu++2gCy3wUrADJn8crvfI="
  APP_NAME: "My App"
  APP_URL: "http://192.168.59.100:32380/api"
  DB_CONNECTION: "mysql"
  DB_DATABASE: "laravel"
  DB_HOST: "mysql"
  DB_PASSWORD: "123456"
  DB_PORT: "3306"
  DB_USERNAME: "root"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "database"