apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
      - name: dir
        hostPath:
          path: /code
      containers:
      - name: php
        image: lucasfer/laravel_app:latest
        envFrom:
          - configMapRef:
              name: laravel-configmap
        volumeMounts:
        - name: dir
          mountPath: /code
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /var/www/. /code/app && chmod o+w /code/app/storage/ -R && cd /code/app/ && php artisan migrate:fresh --seed "]
                # command: ["/bin/sh", "-c", "chmod o+w /code/app/storage/ -R"]
                # command: ["/bin/sh", "-c", "cd /code/app/ && php artisan migrate --seed"]
      initContainers:
      - name: install
        image: busybox
        volumeMounts:
        - name: dir
          mountPath: /code