version: "3.3"

services:
  api:
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    image: api
    container_name: api
    working_dir: /var/www/html
    restart: always
    ports:
      - "8000:80"
    networks: 
      api-network:
        ipv4_address: 20.1.0.100
    depends_on:
      - "mysql"

  mysql:
    image: mysql:5.7.22
    command: --max_allowed_packet=32505856
    container_name: mysql
    hostname: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
    volumes:
      - ~/volumes/api/mysql/data/db/:/var/lib/mysql/
      - ~/volumes/api/mysql/dump/:/docker-entrypoint-initdb.d/ 
    networks:
      api-network:
        ipv4_address: 20.1.0.101

  workers:
    build:
      context: .
      dockerfile: ./.docker/workers/Dockerfile
    image: workers
    container_name: workers
    working_dir: /var/www/html
    restart: always
    networks:
      api-network:
        ipv4_address: 20.1.0.102
    depends_on:
      - "api"

networks:
  api-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 20.1.0.0/24
