version: "3.3"

services:
  nginx_sender:
    build: 
      context: .
      dockerfile: ./environment/nginx/Dockerfile
    image: ngnix
    container_name: nginx_sender
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./environment/nginx/default-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./environment/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks: 
      application-network:
        ipv4_address: 30.1.0.11
    depends_on: 
      - "application_sender"

  application_sender:
    build:
      context: .
      dockerfile: ./environment/application/Dockerfile
    image: application_sender
    container_name: application_sender
    environment:
      CONTAINER_ROLE: app
    volumes:
      - ./:/var/www/html
      - ./environment/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/html
    command: php-fpm
    ports:
      - "9000"
    networks: 
      application-network:
        ipv4_address: 30.1.0.12
    depends_on: 
      - "mysql_sender"

  mysql_sender:
    image: mysql:8.0.36
    command: --max_allowed_packet=32505856
    container_name: mysql_sender
    hostname: mysql_sender
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/lucas/volumes/sender/mysql/data/db/:/var/lib/mysql/
      - /home/lucas/volumes/sender/mysql/dump/:/docker-entrypoint-initdb.d/ 
    networks:
      application-network:
        ipv4_address: 30.1.0.13
  
  # supervisor_sender: 
  #   image: application_sender
  #   container_name: supervisor_sender
  #   environment:
  #     CONTAINER_ROLE: default-queue  
  #   volumes:
  #     - ./:/var/www/html
  #   working_dir: /var/www/html  
  #   networks: 
  #     application-network:
  #       ipv4_address: 30.1.0.14
  #   depends_on:
  #     - "mysql_sender" 

networks:
  application-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 30.1.0.0/24
